### ISSUE TITLE
Can't install addons-linter anymore if python is not installed

### ISSUE THREAD

**Issue by asamuzaK** [mozilla/addons-linter#1668]
### Describe the problem and steps to reproduce it:
When I tried to install (upgrade) addons-linter (Windows 10), installation failed.
Failed at the sharp module install script, and it seems to require Python.

Is sharp really needed?

### What happened?
Installation failed.

### What did you expect to happen?
Complete installation without any error.

### Anything else we should know?
(Please include screenshots and any relevant files.)

install log
```
npm install addons-linter -g
C:\Users\XXX\AppData\Roaming\npm\addons-linter -> C:\Users\XXX\AppData\Roaming\npm\node_modules\addons-linter\bin\addons-linter

> sharp@0.18.1 install C:\Users\XXX\AppData\Roaming\npm\node_modules\addons-linter\node_modules\sharp
> node-gyp rebuild


C:\Users\XXX\AppData\Roaming\npm\node_modules\addons-linter\node_modules\sharp>if not defined npm_config_node_gyp (node "C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\XXX\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\XXX\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\XXX\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\XXX\AppData\Roaming\npm\node_modules\addons-linter\node_modules\sharp
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sharp@0.18.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Roaming\npm-cache\_logs\2017-11-24T03_27_03_213Z-debug.log
```

**Comment by asamuzaK** [comment]
Can we use [probe-image-size](https://www.npmjs.com/package/probe-image-size "probe-image-size") instead of "sharp"?
