### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-linter#2441]
```
Linter › should optionally scan selected files
    AssertError: expected spy, spy, spy to be called in order but were called as spy, spy, spy

      590 | 
      591 |   it('should survive even a 1 column terminal', () => {
    > 592 |     const addonLinter = new Linter({ _: ['bar'] });
          |                          ^
      593 |     addonLinter.collector.addError({
      594 |       code: 'WHATEVER_ERROR',
      595 |       message: 'whatever error message',

      at Object.fail (node_modules/sinon/lib/sinon/assert.js:106:21)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:65:16)
      at Object.assertCallOrder [as callOrder] (node_modules/sinon/lib/sinon/assert.js:136:13)
      at Object._callee17$ (tests/unit/test.linter.js:592:26)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:288:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:114:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
```

**Comment by EnTeQuAk** [comment]
This only happened on appveyor right? Or does it happen on travis too? I haven't seen it much recently

**Comment by wagnerand** [comment]
Yes, so far I have only seen it on appveyor I think.

**Comment by wagnerand** [comment]
Just seen it three times in the latest round of dependency updates.

**Comment by EnTeQuAk** [comment]
We should move to travis windows workers really, appveyor is very unreliable at best. Afaik web-ext already did that so we might be able to steal some config.

**Comment by muffinresearch** [comment]
@wagnerand Is this still an issue?

**Comment by EnTeQuAk** [comment]
Yes, appveyor is still unreliable from time to time.

**Comment by wagnerand** [comment]
For the record I have also seen this failure locally, but it's more rare than on appveyor.

**Comment by wagnerand** [comment]
Still happening:

```
Linter › should optionally scan selected files

    AssertError: expected spy, spy, spy to be called in order but were called as spy, spy, spy

      230 |   it('should optionally scan selected files', async () => {
      231 |     const addonLinter = new Linter({
    > 232 |       _: ['tests/fixtures/webextension_scan_file'],
          |                  ^
      233 |       scanFile: ['subdir/test.js', 'subdir/test2.js'],
      234 |     });
      235 |     // Stub print to prevent output.

      at Object.fail (node_modules/sinon/lib/sinon/assert.js:110:25)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:67:20)
      at Object.assertCallOrder [as callOrder] (node_modules/sinon/lib/sinon/assert.js:140:17)
      at Object.<anonymous> (tests/unit/test.linter.js:232:18)
 ```

https://app.circleci.com/pipelines/github/mozilla/addons-linter/461/workflows/76cec40d-22e9-4b75-9a9c-d6ddb8f8901a/jobs/1057

**Comment by rpl** [comment]
as a side note (mainly because it may be useful to know while investigating this actively): I've just got this intermittent to reproduce one locally while running `npm run test-coverage-once` and so it may be something that it is only be reproduced (or more easily triggered) when the test runs instrumented for the code coverage data collection.
