### ISSUE TITLE
Addon Validation Error: value equal null

### ISSUE THREAD

**Issue by lidel** [mozilla/addons-linter#2834]
### Information

Tried to upload fennec version for android:
[ipfs_companion_beta_aeecbb5_-2.8.4.824_fennec.zip](https://github.com/mozilla/addons/files/3630965/ipfs_companion_beta_aeecbb5_-2.8.4.824_fennec.zip)

Got error without any explanation:

> ![Screenshot_2019-09-19 Validation Results for ipfs_companion_beta_aeecbb5_-2 8 4 824_fennec zip Developer Hub Add-ons for Fi](https://user-images.githubusercontent.com/157609/65240718-33523380-dae2-11e9-8fd9-9e7f44efa60c.png)

* This error occurred during the submission of a new version of an existing add-on
* Add-on is unlisted (self-hosted beta channel)
* The URL where you submitted the add-on: https://addons.mozilla.org/en-US/developers/addon/9d155c1c2b6147c39860/versions/submit/
* The approximate time submitted the add-on, with timezone: 2019-09-19 13:30 CEST

## Bug?

I think it is because of `"incognito": null` in `manifest.json`. Addon loads fine into Firefox, however `addons-linter` does not support `null` keys and returns an error:

```console
$ web-ext lint
Applying config files: ./package.json, ./web-ext-config.js
Cannot convert undefined or null to object

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at ManifestJSONParser.call [as checkCompatInfo] (/home/lidel/project/ipfs-companion/node_modules/addons-linter/dist/webpack:/src/parsers/manifestjson.js:153:43)
    at ManifestJSONParser.checkCompatInfo [as _validate] (/home/lidel/project/ipfs-companion/node_modules/addons-linter/dist/webpack:/src/parsers/manifestjson.js:401:16)
    at new _validate (/home/lidel/project/ipfs-companion/node_modules/addons-linter/dist/webpack:/src/parsers/manifestjson.js:94:12)
    at Linter._callee$ (/home/lidel/project/ipfs-companion/node_modules/addons-linter/dist/webpack:/src/linter.js:255:30)
    at tryCatch (/home/lidel/project/ipfs-companion/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/lidel/project/ipfs-companion/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/lidel/project/ipfs-companion/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/lidel/project/ipfs-companion/node_modules/addons-linter/dist/webpack:/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:1)
    at _next (/home/lidel/project/ipfs-companion/node_modules/addons-linter/dist/webpack:/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:1)
```

### Solution?

I think `null` values should be allowed, it is a valid JSON.

**Comment by Rob--W** [comment]
Still reproduced with latest `web-ext` and the latest AMO: https://addons-dev.allizom.org/en-US/developers/addon/submit/upload-listed

TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at ManifestJSONParser.checkCompatInfo (/path/to/web-ext/node_modules/addons-linter/dist/webpack:/src/parsers/manifestjson.js:160:43)
    at ManifestJSONParser._validate (/path/to/web-ext/node_modules/addons-linter/dist/webpack:/src/parsers/manifestjson.js:417:16)
    at new ManifestJSONParser (/path/to/web-ext/node_modules/addons-linter/dist/webpack:/src/parsers/manifestjson.js:101:12)
    at Linter._callee$ (/path/to/web-ext/node_modules/addons-linter/dist/webpack:/src/linter.js:255:30)
    at tryCatch (/path/to/web-ext/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/path/to/web-ext/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.<computed> [as next] (/path/to/web-ext/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/path/to/web-ext/node_modules/addons-linter/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/path/to/web-ext/node_modules/addons-linter/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

**Comment by Yrkan** [comment]
Should null be accepted ?
According to this incognito is an enum of **["spanning", "split", "not allowed"]**
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito

While looking this up i found another potential bug, the MDN docs say that it should accept ["spanning", "split", "not allowed"] but the current validation accepts only **["spanning", "not allowed"]**

I opened an issue for this  **#3417**

**Comment by willdurand** [comment]
@Rob--W what do you think we should do here? According to the comment above, `null` isn't valid.

**Comment by rpl** [comment]
> @Rob--W what do you think we should do here? According to the comment above, `null` isn't valid.

@willdurand I just tried to reproduce this locally and I got a nicer validation result with incognito set to null:

```
 ./bin/addons-linter tmp/test-incognito-null
Validation Summary:

errors          2
notices         0
warnings        0

ERRORS:

Code                     Message                                  Description                                                   File            Line   Column
MANIFEST_FIELD_INVALID   "/incognito" should be string            See https://mzl.la/1ZOhoEN (MDN Docs) for more information.   manifest.json
JSON_INVALID             "/incognito" should be equal to one of   Your JSON file could not be parsed.
                         the allowed values
```

This validation result seems nice enough and so if the original error can't be reproduced anymore I would keep this behavior.

**Comment by Rob--W** [comment]
@rpl That warning looks good enough to me.
