### ISSUE TITLE
(Feature request) Add option to respect .gitignore when linting

### ISSUE THREAD

**Issue by carterworks** [mozilla/addons-linter#5390]
### Describe the problem and steps to reproduce it:

(Please include as many details as possible.)

I have a large corporate repository with a deep node_modules folder. I am trying to make my project pass `addons-linter`.

However, when I run `addons-linter .` from the repo root, I get the following error:

```
$ addons-linter .
File ".parcel-cache/data.mdb" is too large. Aborting

<repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:54
                throw new Error(`File "${_path}" is too large. Aborting`);
                      ^
Error: File ".parcel-cache/data.mdb" is too large. Aborting
    at Directory.<anonymous> (<repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:54:23)
    at Generator.next (<anonymous>)
    at <repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (<repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:4:12)
    at Directory.getPath (<repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:49:16)
    at Directory.<anonymous> (<repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:98:41)
    at Generator.next (<anonymous>)
    at <repository  root>/node_modules/addons-linter/node_modules/addons-scanner-utils/dist/io/directory.js:8:71
    at new Promise (<anonymous>)
```
I have also gotten an error that reports certain paths in the `node_modules` folder being too long

When run on generated code, I get the following message:

```
$ addons-linter dist/
Validation Summary:

errors          4              
notices         0              
warnings        5              

ERRORS:

Code             Message                       Description                                                                                                    File                          Line   Column
FILE_TOO_LARGE   File is too large to parse.   This file is not binary and is too large to parse. Files larger than 4MB will not be parsed. Consider moving   xlsx.82cb7f3b.js                           
                                               large lists of data out of JavaScript files and into JSON files, or splitting very large files into smaller                                               
                                               ones.                                                                                                                                                     
FILE_TOO_LARGE   File is too large to parse.   This file is not binary and is too large to parse. Files larger than 4MB will not be parsed. Consider moving   src/login/login.e4c88f8d.js                
                                               large lists of data out of JavaScript files and into JSON files, or splitting very large files into smaller                                               
                                               ones.                                                                                                                                                     
FILE_TOO_LARGE   File is too large to parse.   This file is not binary and is too large to parse. Files larger than 4MB will not be parsed. Consider moving   content.40629bcd.js                        
                                               large lists of data out of JavaScript files and into JSON files, or splitting very large files into smaller                                               
                                               ones.                                                                                                                                                     
FILE_TOO_LARGE   File is too large to parse.   This file is not binary and is too large to parse. Files larger than 4MB will not be parsed. Consider moving   src/app/index.8a47dbb3.js                  
                                               large lists of data out of JavaScript files and into JSON files, or splitting very large files into smaller                                               
                                               ones.     
```

So I would prefer to run it on the un-bundled code.

I think the easiest way for that to happen is if there is an option to ignore files that are ignored by the `.gitignore` file.

**Comment by Rob--W** [comment]
We intentionally prevent files from affecting linter behavior because that would enable extension files to bypass the linter. Moreover, a file being in .gitignore is not automatically a sign that it should be ignored for linting. An obvious example is where the add-on file is generated from multiple other files, potentially libraries from npm.

`web-ext lint` builds upon `addons-linter` and offers the `--ignore-files` option. Any option that `web-ext` accepts can also be configured through a (project-specific) config file, which enables you to ignore files by default.

Documentation:
- https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#web-ext-lint
- https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#global-options
- https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#use-the-configuration-file
