### ISSUE TITLE
npm test fails on fresh clone

### ISSUE THREAD

**Issue by groovecoder** [mozilla/addons-linter#868]
I cloned this repo locally, ran `npm install`, then tried to run `npm test` ...
```
Running "mochaTest:coverage" (mochaTest) task
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/c>> Mocha exploded!
>> Error: Cannot find module 'dispensary'
>>     at Function.Module._resolveFilename (module.js:438:15)
>>     at Function.Module._load (module.js:386:25)
>>     at Module.require (module.js:466:17)
>>     at require (internal/module.js:20:19)
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/external "dispensary":1:1)
>>     at _webpack_require_ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/linter.js:9:2449)
>>     at _webpack_require_ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
>>     at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/parsers/test.installrdf.js:4:1)
>>     at _webpack_require_ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
>>     at webpackContext (/Users/lcrouch/code/addons-linter/dist/webpack:/tests .*:58:1)
>>     at Array.forEach (native)
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/runner.js:7:16)
>>     at _webpack_require_ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
>>     at /Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1)
>>     at Module._compile (module.js:541:32)
>>     at Object.Module._extensions..js (module.js:550:10)
>>     at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>>     at tryModuleLoad (mode/addons-linter/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/external "bunyan":1:1)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/logger.js:9:218)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/io/crx.js:9:2181)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/src/io/index.js:9:143)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/io/test.crx.js:3:1)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at webpackContext (/Users/lcrouch/code/addons-linter/dist/webpack:/tests .*:58:1)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/runner.js:7:16)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at /Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:217:14)
    at MochaWrapper.run (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
    at /Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
    at capture (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:255:15)
    at Object.thisTask.fn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:73:16)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:294:30)
    at Task.runTaskFn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:244:24)
    at Task.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:293:12)
    at /Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:220:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.js:415:12)
>>     at Function.Module._load (module.js:407:3)
>>     at Module.require (module.js:466:17)
>>     at require (internal/module.js:20:19)
>>     at /Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:220:27
>>     at Array.forEach (native)
>>     at Mocha.loadFiles (/Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:217:14)
>>     at MochaWrapper.run (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
>>     at /Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
>>     at capture (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modulesodule.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/external "bunyan":1:1)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/logger.js:9:218)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/io/crx.js:9:2181)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/src/io/index.js:9:143)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/io/test.crx.js:3:1)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at webpackContext (/Users/lcrouch/code/addons-linter/dist/webpack:/tests .*:58:1)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/runner.js:7:16)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at /Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:217:14)
    at MochaWrapper.run (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
    at /Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
    at capture (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:255:15)
    at Object.thisTask.fn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:73:16)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:294:30)
    at Task.runTaskFn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:244:24)
    at Task.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:293:12)
    at /Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:220:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/bunyan/lib/bunyan.js:79:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/external "bunyan":1:1)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/logger.js:9:218)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/src/io/crx.js:9:2181)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.module.exports._typeof2 (/Users/lcrouch/code/addons-linter/dist/webpack:/src/io/index.js:9:143)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/io/test.crx.js:3:1)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at webpackContext (/Users/lcrouch/code/addons-linter/dist/webpack:/tests .*:58:1)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/tests/runner.js:7:16)
    at __webpack_require__ (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:19:1)
    at /Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/dist/webpack:/webpack/bootstrap c69f661089aa0c8093c2:39:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (/Users/lcrouch/code/addons-linter/node_modules/grunt/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/lcrouch/code/addons-linter/node_modules/mocha/lib/mocha.js:217:14)
    at MochaWrapper.run (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/lib/MochaWrapper.js:51:15)
    at /Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:86:20
    at capture (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:33:5)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt-mocha-test/tasks/mocha-test.js:81:5)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:255:15)
    at Object.thisTask.fn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:73:16)
    at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:294:30)
    at Task.runTaskFn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:244:24)
    at Task.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:293:12)
    at /Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:220:11
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9) code: 'MODULE_NOT_FOUND' }
/grunt/lib/grunt/task.js:255:15)
>>     at Object.thisTask.fn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/grunt/task.js:73:16)
>>     at Object.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:294:30)
>>     at Task.runTaskFn (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:244:24)
>>     at Task.<anonymous> (/Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:293:12)
>>     at /Users/lcrouch/code/addons-linter/node_modules/grunt/lib/util/task.js:220:11
>>     at _combinedTickCallback (internal/process/next_tick.js:67:7)
>>     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
Warning: Task "mochaTest:coverage" failed. Use --force to continue.
```

**Comment by groovecoder** [comment]
Note: I got a similar error when I tried `npm run test-no-coverage` ... i.e.,
```
Error: Module did not self-register.
...
>> Error: Cannot find module 'dispensary'
...
{ Error: Cannot find module './build/default/DTraceProviderBindings'
...
Warning: Task "mochaTest:test" failed. Use --force to continue.
```

**Comment by pdehaan** [comment]
@groovecoder What version of Node/npm are you using?

**Comment by groovecoder** [comment]
I tried v6.1.0 and v5.11.1

**Comment by pdehaan** [comment]
@groovecoder Very curious. I was unable to reproduce after doing an `$ rm -rf node_modules && npm i` then `$ npm test`.

```sh
$ node --version # v6.3.0
$ npm --version # 3.10.3
```

The [installation instructions in the README.md](https://github.com/mozilla/addons-linter#npm-scripts-and-grunt-tasks) make reference to globally installing **grunt-cli**, but it looks like we correctly have **grunt@1.0.1** in the [package.json](https://github.com/mozilla/addons-linter/blob/master/package.json#L40), so we should be using the locally installed Grunt instead of a globally installed Grunt.

```sh
$ grunt --version
# grunt-cli v0.1.13
# grunt v1.0.1
```

Do you get the same results if you run `$ grunt test` directly?

Here's what I get when I run `$ npm ls --depth 0` from the Terminal:

```sh
$ npm ls --depth 0

addons-linter@0.14.3 /Users/pdehaan/dev/github/mozilla/addons-linter
├── ajv@4.3.0
├── babel-core@6.10.4
├── babel-eslint@6.1.2
├── babel-istanbul@0.11.0
├── babel-istanbul-loader@0.1.0
├── babel-loader@6.2.4
├── babel-plugin-transform-class-properties@6.11.5
├── babel-plugin-transform-es2015-modules-commonjs@6.11.5
├── babel-polyfill@6.9.1
├── babel-preset-es2015@6.9.0
├── babel-preset-stage-2@6.11.0
├── bunyan@1.8.1
├── chai@3.5.0
├── chalk@1.1.3
├── cheerio@0.20.0
├── columnify@1.5.4
├── coveralls@2.11.12
├── crx-parser@0.1.2
├── dispensary@0.7.0
├── es6-promisify@4.1.0
├── eslint@3.2.2
├── esprima@2.7.2
├── first-chunk-stream@2.0.0
├── gfm.css@1.1.1
├── grunt@1.0.1
├── grunt-contrib-clean@1.0.0
├── grunt-contrib-copy@1.0.0
├── grunt-coveralls@1.0.1
├── grunt-eslint@19.0.0
├── grunt-gh-pages@1.1.0
├── grunt-mocha-test@0.12.7
├── grunt-newer@1.2.0
├── grunt-webpack@1.0.14
├── isparta@4.0.0
├── json-loader@0.5.4
├── load-grunt-configs@1.0.0
├── load-grunt-tasks@3.5.0
├── lodash.clonedeep@4.4.1
├── markdown-it@7.0.0
├── markdown-it-anchor@2.5.0
├── markdown-it-emoji@1.2.0
├── mocha@3.0.0
├── mocha-multi@0.9.1
├── postcss@5.1.1
├── relaxed-json@1.0.0
├── semver@5.3.0
├── sha.js@2.4.5
├── shelljs@0.7.3
├── sinon@1.17.5
├── source-map-support@0.4.2
├── strip-bom-stream@2.0.0
├── url-parse@1.1.1
├── webpack@1.13.1
├── webpack-dev-server@1.14.0
├── xmldom@0.1.22
├── yargs@4.8.1
└── yauzl@2.6.0

npm ERR! missing: shelljs@^0.6.0, required by eslint@3.1.1
npm ERR! missing: shelljs@^0.6.0, required by eslint@3.2.2
```

**Comment by tofumatt** [comment]
This is a bit odd as Travis can check out a fresh version and run the tests fine.

I recall seeing a `./build/default/DTraceProviderBindings` error recently as well. I ended up changing to `nvm`, reinstalling my modules, and it worked. I think it might've been related to a recent OS X update? I dunno 🙁

**Comment by muffinresearch** [comment]
You might get this if you upgraded node or are using a different version to the one you installed the node modules with. 

You could try blowing away the `node_modules`, run `npm install` again and re-run the tests and see if that helps?

**Comment by groovecoder** [comment]
I did `npm cache clean` and also got a new machine and this error is gone. So I'm willing to say it was my (old) machine.
